version: '2.4'
services:
    redis:
        image: redis:alpine
        networks:
            - my-demo-project-network

    db:
        image: mariadb:10.5
        working_dir: /application
        command: [ mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb-file-format=Barracuda, --innodb-large-prefix=1, --innodb-file-per-table=1 ]
        volumes:
            - my-demo-project-db:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
            - "MYSQL_DATABASE=${MYSQL_DATABASE}"
            - "MYSQL_USER=${MYSQL_USER}"
            - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
        networks:
            - my-demo-project-network

    nginx:
        image: nginx:latest
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/config/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - my-demo-project-network

    php-debug:
        image: pimcore/pimcore:PHP8.0-fpm-debug
        volumes:
            - .:/var/www/html:cached
        environment:
            - PHP_IDE_CONFIG="serverName=localhost"
            - APP_ENV=dev
        networks:
            - my-demo-project-network

volumes:
    my-demo-project-db:

networks:
    my-demo-project-network:
